import {BitFlag} from '$lib/bitfield';

export const flags = {
  ALL:                    BitFlag(0),
  READ_ARTICLE:           BitFlag(1),
  WRITE_ARTICLE:          BitFlag(2),
  EDIT_ARTICLE:           BitFlag(3),
  DELETE_ARTICLE:         BitFlag(4),
  MANAGE_ARTICLE:         BitFlag(5),
  VIEW_ARTICLELIST:       BitFlag(6),
  READ_COMMENT:           BitFlag(7),
  VIEW_BOARDLIST:         BitFlag(8),
  WRITE_COMMENT:          BitFlag(9),
  EDIT_COMMENT:           BitFlag(10),
  DELETE_COMMENT:         BitFlag(11),
  MANAGE_COMMENT:         BitFlag(12),
  NEW_BOARD:              BitFlag(13),
  DELETE_BOARD:           BitFlag(14),
  RENAME_BOARD:           BitFlag(15),
  LOCK_BOARD:             BitFlag(16),
  BAN_USER_PERMANENTLY:   BitFlag(17),
  BAN_USER_TEMPORARY:     BitFlag(18),
  ADULT:                  BitFlag(19),
  REORDER_BOARD:          BitFlag(20),
  CHANGE_PUB_BOARD:       BitFlag(21),
  CHANGE_USER_GRANT:      BitFlag(22),
  CHANGE_USER_PERMISSION: BitFlag(23),
  CHANGE_USERNAME:        BitFlag(24),
  ADD_TAG:                BitFlag(25),
  REMOVE_TAG:             BitFlag(26),
  REMOVE_OWN_TAG:         BitFlag(27),
  VIEW_TAG_OWNER:         BitFlag(28),
  MANAGE_BOARD:           BitFlag(29),
};